# Glioma Grading Clinical and Mutation Features Dataset

Gliomas are the common primary brain tumors. They are graded as Lower-Grade Glioma(LGG) or Glioblastoma Multiforme(GBM) depending on the histological/imaging criteria. 

Clinical and molecular/mutation factors are also very crucial for the grading process.In this dataset, the most frequently mutated 20 genes and 4 clinical features are considered from TCGA-LGG and TCGA-GBM brain glioma projects. 

The task is to determine whether a patient is LGG or GBM with a given clinical and molecular/mutation features. The objective is to find the optimal subset of mutation genes and clinical features for the glioma grading process to improve performance and reduce costs.

## Dataset

The dataset is a Giloma Grading Clinical and Mutation Features Dataset, from UCI repository.

Link: https://archive-beta.ics.uci.edu/dataset/759/glioma+grading+clinical+and+mutation+features+dataset

## Importing the dataset

In [4]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [5]:
df = pd.read_csv("D:\\glioma+grading+clinical+and+mutation+features+dataset\\TCGA_GBM_LGG_Mutations_all.csv")
df.head()

,Grade,Project,Case_ID,Gender,Age_at_diagnosis,Primary_Diagnosis,Race,IDH1,TP53,ATRX,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,LGG,TCGA-LGG,TCGA-DU-8164,Male,51 years 108 days,"Oligodendroglioma, NOS",white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
1,LGG,TCGA-LGG,TCGA-QH-A6CY,Male,38 years 261 days,Mixed glioma,white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
2,LGG,TCGA-LGG,TCGA-HW-A5KM,Male,35 years 62 days,"Astrocytoma, NOS",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
3,LGG,TCGA-LGG,TCGA-E1-A7YE,Female,32 years 283 days,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,MUTATED,NOT_MUTATED
4,LGG,TCGA-LGG,TCGA-S9-A6WG,Male,31 years 187 days,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED

## Eliminating null values

According to the dataset there are no null values present in the dataset

In [6]:
df.isna().sum()

Grade                0
Project              0
Case_ID              0
Gender               0
Age_at_diagnosis     0
Primary_Diagnosis    0
Race                 0
IDH1                 0
TP53                 0
ATRX                 0
PTEN                 0
EGFR                 0
CIC                  0
MUC16                0
PIK3CA               0
NF1                  0
PIK3R1               0
FUBP1                0
RB1                  0
NOTCH1               0
BCOR                 0
CSMD3                0
SMARCA4              0
GRIN2A               0
IDH2                 0
FAT4                 0
PDGFRA               0
dtype: int64

In [14]:
df.Gender.unique()

array(['Male', 'Female', '--'], dtype=object)

In [11]:
df.Race.unique()

array(['white', 'asian', 'black or african american', '--',
       'not reported', 'american indian or alaska native'], dtype=object)

In [15]:
df.IDH2.unique()

array(['NOT_MUTATED', 'MUTATED'], dtype=object)

But on close examination of the datast, we can observe that there are two strings used in place of a null value and they are **--** and **not reported.** 

Thus we will pass these strings to *na_values* parameter of the pandas DataFrame, so that pandas will recognises these special strigs as null values.

In [16]:
df = pd.read_csv("D:\\glioma+grading+clinical+and+mutation+features+dataset\\TCGA_GBM_LGG_Mutations_all.csv", na_values = ["--","not reported"])
df.head()

,Grade,Project,Case_ID,Gender,Age_at_diagnosis,Primary_Diagnosis,Race,IDH1,TP53,ATRX,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,LGG,TCGA-LGG,TCGA-DU-8164,Male,51 years 108 days,"Oligodendroglioma, NOS",white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
1,LGG,TCGA-LGG,TCGA-QH-A6CY,Male,38 years 261 days,Mixed glioma,white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
2,LGG,TCGA-LGG,TCGA-HW-A5KM,Male,35 years 62 days,"Astrocytoma, NOS",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
3,LGG,TCGA-LGG,TCGA-E1-A7YE,Female,32 years 283 days,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,MUTATED,NOT_MUTATED
4,LGG,TCGA-LGG,TCGA-S9-A6WG,Male,31 years 187 days,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED

Renaming the **Age_at_diagnonis** column to **age**

In [18]:
df.rename(columns = {"Age_at_diagnosis":"age"}, inplace = True)

Changing the format of the elements in age column from string to numerical values.

In [19]:
df['age'] = df['age'].replace(' years ', '.', regex=True)
df['age'] = df['age'].replace(' years', '', regex=True)
df['age'] = df['age'].replace(' days','', regex = True)

In [20]:
df.age.unique()

array(['51.108', '38.261', '35.62', '32.283', '31.187', '33.78', '35.68',
       '44.239', '33.350', '87', '51.328', '54.95', '52.214', '47.123',
       '34.132', '40.192', '53.352', '41.70', '43.161', '37.159',
       '47.173', '31.8', '25.191', '66.305', '56.250', '35.362', '51.363',
       '37.32', '54.183', '32.76', '65.28', '43.131', '51.59', '43.221',
       '25.214', '45.24', '50.153', '27.166', '53.252', '46.144',
       '24.239', nan, '34.70', '29.198', '45.124', '62.90', '46.224',
       '36.247', '62.202', '70.159', '53.41', '48.124', '40.69', '40.7',
       '20.359', '57.200', '38.322', '52.192', '56.104', '59.275',
       '67.107', '48.346', '59.254', '58.147', '27.247', '51.230',
       '74.11', '52.230', '61.62', '66.146', '42.32', '31.344', '48.268',
       '33.340', '34.213', '24.54', '55.48', '27.323', '29.32', '39.131',
       '70.3', '30.338', '39.178', '25.41', '48.160', '57.17', '34.307',
       '58.137', '55.208', '60.49', '38.13', '56.113', '54.180', '31.152',
       '54.146', '52.241', '33.54', '42.173', '20.75', '64.106', '29.232',
       '36.222', '31.362', '36.67', '32.173', '38.292', '29.298', '41.76',
       '35.189', '33.39', '32.50', '49.276', '69.217', '14.154', '33.349',
       '47.92', '33.58', '63.364', '62.205', '37.83', '53.183', '53.74',
       '45.76', '33.331', '53.359', '52.156', '64.304', '71.70', '40.300',
       '36.354', '25.249', '63.170', '40.310', '47.215', '73.241',
       '24.51', '48.342', '41.325', '36.189', '45.334', '44.204', '27.6',
       '50.181', '42.141', '40.248', '62.192', '33.195', '46.42',
       '41.117', '47.333', '56.159', '38.64', '60.64', '29.150', '59.196',
       '44.66', '69.60', '63.253', '43.142', '61.316', '39.66', '31.315',
       '51.164', '41.203', '60.360', '74.158', '63.81', '66.170',
       '51.312', '39.62', '38.111', '37.92', '30.32', '54.143', '36.357',
       '48.197', '29.81', '32.135', '44.35', '30.329', '57.287', '19.55',
       '70.242', '63.67', '41.255', '29.291', '42.318', '51.172', '38.25',
       '28.344', '32.166', '26.43', '67.329', '40.326', '59.295', '58.16',
       '56.171', '20.276', '49.296', '37.31', '48.243', '71.227',
       '43.316', '27.309', '25.78', '30.126', '47.335', '31.262',
       '30.295', '30.276', '24.146', '41.66', '34.189', '56.155',
       '39.348', '23.3', '31.273', '17.271', '64.110', '27.221', '69.64',
       '37.51', '44.92', '25.97', '29.235', '26.209', '47.294', '39.252',
       '35.26', '33.287', '74.204', '50.167', '65.314', '60.116',
       '34.346', '44.229', '21.243', '55.87', '43.361', '36.49', '70.100',
       '23.352', '43.195', '30.264', '38.140', '34.188', '55.92',
       '30.238', '61.68', '44.344', '35.238', '68.129', '44.206', '38.89',
       '36.304', '52.32', '36.183', '33.176', '60.119', '44.90', '58.157',
       '33.364', '62.235', '44.226', '36.311', '29.132', '25.282',
       '20.307', '61.305', '41.222', '47.224', '59.212', '48.311',
       '38.24', '27.58', '58.15', '26.118', '44.209', '32.196', '22.305',
       '25.316', '34.27', '24.278', '30.348', '39.280', '22.236',
       '53.286', '30.355', '37.239', '36.73', '41.314', '57.201',
       '52.243', '31.346', '32.167', '44.131', '40.106', '44.263', '39.5',
       '62.93', '45.296', '48.131', '49.187', '38.194', '28.115',
       '38.273', '37.81', '41.179', '60.15', '50.232', '75.292', '43.143',
       '52.63', '38.333', '66.344', '30.57', '59.262', '35.37', '38.203',
       '42.310', '59.166', '26.94', '58.266', '31.10', '30.161', '45.231',
       '37.166', '34.162', '34.339', '32.53', '66.176', '46.89', '38.326',
       '33.213', '40.61', '52.145', '59.359', '58.55', '43.281', '33.192',
       '55.40', '43.226', '60.123', '33.332', '48.80', '70.205', '53.197',
       '66.136', '36.275', '40.49', '73.103', '36.165', '74.56', '43.145',
       '40.323', '38.128', '54.291', '63.54', '62.303', '35.53', '39.174',
       '29.341', '46.333', '46.110', '51.329', '54.221', '42.91',
       '64.108', '29.220', '65.195', '41.91', '31.206', '58.5', '54.318',
       '28.26', '20.116', '34.160', '54.198', '45.259', '48.325', '29.86',
       '22.8', '32.161', '40.50', '61.47', '57.276', '54.100', '56.317',
       '34.139', '27.289', '37.149', '43.332', '41.10', '33.104', '39.35',
       '31.300', '67.219', '30.140', '48.212', '50.302', '45.34',
       '47.299', '32.158', '26.171', '29.213', '28.79', '66.16', '39.304',
       '33.238', '60.75', '35.65', '35.45', '58.168', '26.50', '30.113',
       '38.82', '35.325', '39.291', '55.306', '49.337', '50.59', '52.163',
       '51.121', '61.285', '52.149', '35.66', '47.266', '35.70', '31.105',
       '31.35', '37.50', '37.97', '42.249', '32.116', '61.22', '48.78',
       '34.42', '30.252', '30.86', '28.195', '47.226', '35.91', '23.171',
       '49.264', '36.78', '54.268', '22.300', '42.5', '28.213', '25.232',
       '66.3', '46.181', '57.310', '43.22', '49.309', '33.99', '27.306',
       '62.166', '55.153', '37.285', '37.107', '32.122', '38.143',
       '42.289', '47.165', '54.227', '29.49', '39.359', '28.249',
       '23.108', '21.276', '38.229', '49.302', '38.308', '22.205',
       '67.215', '73.329', '62.100', '57.314', '30.334', '24.181',
       '20.84', '41.116', '53.258', '34.237', '51.350', '57.364',
       '31.176', '57.141', '49.263', '60.106', '73.250', '64.298',
       '73.164', '33.239', '67.151', '72.74', '69.124', '79.39', '68.7',
       '76.5', '82.14', '58.9', '52.251', '81.217', '74.172', '76.87',
       '57.110', '67.121', '63.313', '64.143', '69.50', '66.28', '54.347',
       '60.114', '45.230', '36.219', '49.174', '69.219', '54.340',
       '58.327', '61.183', '64.191', '65.309', '60.298', '53.309',
       '39.193', '58.227', '56.172', '65.344', '36.59', '72.192',
       '48.348', '39.157', '54.176', '63.333', '66.159', '52.97',
       '89.105', '54.242', '60.262', '77.116', '60.264', '80.61',
       '51.264', '53.145', '43.313', '74.144', '76.118', '49.228',
       '48.333', '68.334', '74.359', '69.211', '64.192', '58.144',
       '47.88', '61.282', '75.194', '52.246', '47.199', '21.288',
       '72.169', '68.108', '67', '52.238', '59.11', '59.149', '48.362',
       '76.58', '72.193', '51.113', '67.187', '82.115', '64.209',
       '75.265', '85.221', '73.105', '78.273', '45.136', '42.225',
       '53.299', '68.290', '43.245', '59.289', '52.137', '61.244',
       '40.207', '63.263', '63.307', '70.98', '59.362', '56.101',
       '62.190', '24.83', '72.345', '67.161', '54.200', '86.155',
       '62.222', '63.97', '58.200', '60.5', '67.17', '23.310', '58.59',
       '64.18', '65.37', '61.32', '52.161', '77.139', '58.280', '78.264',
       '63.122', '63.86', '23.133', '65.94', '50.79', '55.209', '60.258',
       '62.220', '69.95', '56.187', '76.72', '76.252', '86.8', '69.80',
       '59.219', '75.337', '57.202', '69.257', '45.226', '47.130',
       '74.57', '78.93', '59.64', '21.266', '81.34', '70.60', '62.153',
       '75.191', '60.136', '63.53', '61.52', '47.71', '76.150', '84.287',
       '77.153', '48.182', '69.223', '56.12', '76.171', '70.117',
       '34.267', '68.341', '54.216', '74.313', '73.193', '57.112',
       '44.230', '83.265', '74.291', '51.275', '52.60', '73.102',
       '81.307', '78.94', '57.312', '53.147', '50.330', '78.56', '76.236',
       '57.118', '36.108', '72.284', '31.11', '65.66', '63.201', '49.351',
       '59.311', '69.232', '62.304', '52.270', '56.294', '81.168',
       '40.293', '81.319', '50.171', '38.8', '48.183', '51.86', '66.341',
       '71.315', '24.156', '63.195', '69.116', '78.7', '30.155', '52.288',
       '65.57', '78.271', '61.37', '50.173', '39.57', '66.81', '49.6',
       '54.78', '58.48', '73.4', '53.303', '63.292', '66.191', '49.322',
       '59.335', '54.327', '57.274', '59.157', '44.55', '58.14', '65.18',
       '67.34', '75.172', '88.209', '53.85', '75.126', '66.269', '51.51',
       '40.360', '58.6', '57.29', '55.144', '40.268', '40.206', '54.89',
       '53.136', '56.9', '59.306', '75.118', '59.10', '44.135', '46.236',
       '68.248', '30.340', '36.302', '78.270', '83.235', '51.201',
       '63.118', '59.227', '53.233', '74.83', '60.246', '54.295', '63.9',
       '58.308', '60.274', '71.257', '75.78', '50.309', '67.6', '60.358',
       '65.143', '51.90', '45.301', '39.316', '70.245', '73.133',
       '65.360', '72.251', '61.177', '65.22', '30.327', '64.50', '55.267',
       '79.123', '74.294', '63.24', '81.21', '53.86', '69.343', '60.342',
       '55.214', '75.342', '47.349', '71.148', '25.82', '61.247',
       '47.302', '50.129', '72.97', '31.7', '86.216', '38.214', '72.302',
       '55.46', '66.320', '55.361', '72.57', '33.7', '83.114', '43.259',
       '68.224', '79.183', '67.326', '49.298', '66.256', '68.221',
       '47.52', '61.218', '49.157', '67.120', '32.268', '65.41', '66.213',
       '62.281', '50.16', '34.111', '61.11', '77.353', '54.101', '51.32',
       '53.8', '78.253', '46.337', '52.244', '48.249', '51.205', '62.41',
       '58.20', '61.112', '66.111', '64.43', '56.114', '77.325', '85.65',
       '77.178', '63.121', '76.221'], dtype=object)

In [21]:
new_age = list()
for x in df.age:
    try:
        p = x.index('.')
        new_age.append(float(x[:p]) + round(float(x[p+1:]) / 365, 2))
    except ValueError:
        new_age.append(float(x))
    except AttributeError:
        new_age.append(x)
len(new_age), len(df.age)

(862, 862)

In [22]:
df["age"]=new_age

In [23]:
df.age.unique()

array([51.3 , 38.72, 35.17, 32.78, 31.51, 33.21, 35.19, 44.65, 33.96,
       87.  , 51.9 , 54.26, 52.59, 47.34, 34.36, 40.53, 53.96, 41.19,
       43.44, 37.44, 47.47, 31.02, 25.52, 66.84, 56.68, 35.99, 51.99,
       37.09, 54.5 , 32.21, 65.08, 43.36, 51.16, 43.61, 25.59, 45.07,
       50.42, 27.45, 53.69, 46.39, 24.65,   nan, 34.19, 29.54, 45.34,
       62.25, 46.61, 36.68, 62.55, 70.44, 53.11, 48.34, 40.19, 40.02,
       20.98, 57.55, 38.88, 52.53, 56.28, 59.75, 67.29, 48.95, 59.7 ,
       58.4 , 27.68, 51.63, 74.03, 52.63, 61.17, 66.4 , 42.09, 31.94,
       48.73, 33.93, 34.58, 24.15, 55.13, 27.88, 29.09, 39.36, 70.01,
       30.93, 39.49, 25.11, 48.44, 57.05, 34.84, 58.38, 55.57, 60.13,
       38.04, 56.31, 54.49, 31.42, 54.4 , 52.66, 33.15, 42.47, 20.21,
       64.29, 29.64, 36.61, 31.99, 36.18, 32.47, 38.8 , 29.82, 41.21,
       35.52, 33.11, 32.14, 49.76, 69.59, 14.42, 47.25, 33.16, 64.  ,
       62.56, 37.23, 53.5 , 53.2 , 45.21, 33.91, 53.98, 52.43, 64.83,
       71.19, 40.82, 36.97, 25.68, 63.47, 40.85, 47.59, 73.66, 24.14,
       48.94, 41.89, 36.52, 45.92, 44.56, 27.02, 50.5 , 42.39, 40.68,
       62.53, 33.53, 46.12, 41.32, 47.91, 56.44, 38.18, 60.18, 29.41,
       59.54, 44.18, 69.16, 63.69, 43.39, 61.87, 39.18, 31.86, 51.45,
       41.56, 60.99, 74.43, 63.22, 66.47, 51.85, 39.17, 38.3 , 37.25,
       30.09, 54.39, 36.98, 48.54, 29.22, 32.37, 44.1 , 30.9 , 57.79,
       19.15, 70.66, 63.18, 41.7 , 29.8 , 42.87, 51.47, 38.07, 28.94,
       32.45, 26.12, 67.9 , 40.89, 59.81, 58.04, 56.47, 20.76, 49.81,
       37.08, 48.67, 71.62, 43.87, 27.85, 25.21, 30.35, 47.92, 31.72,
       30.81, 30.76, 24.4 , 41.18, 34.52, 56.42, 39.95, 23.01, 31.75,
       17.74, 64.3 , 27.61, 69.18, 37.14, 44.25, 25.27, 26.57, 47.81,
       39.69, 35.07, 33.79, 74.56, 50.46, 65.86, 60.32, 34.95, 44.63,
       21.67, 55.24, 43.99, 36.13, 70.27, 23.96, 43.53, 30.72, 38.38,
       55.25, 30.65, 61.19, 44.94, 35.65, 68.35, 38.24, 36.83, 52.09,
       36.5 , 33.48, 60.33, 58.43, 34.  , 62.64, 44.62, 36.85, 29.36,
       25.77, 20.84, 61.84, 41.61, 47.61, 59.58, 48.85, 27.16, 26.32,
       44.57, 32.54, 22.84, 25.87, 34.07, 24.76, 30.95, 39.77, 22.65,
       53.78, 30.97, 37.65, 36.2 , 41.86, 52.67, 31.95, 32.46, 44.36,
       40.29, 44.72, 39.01, 45.81, 48.36, 49.51, 38.53, 28.32, 38.75,
       37.22, 41.49, 60.04, 50.64, 75.8 , 52.17, 38.91, 66.94, 30.16,
       59.72, 35.1 , 38.56, 42.85, 59.45, 26.26, 58.73, 31.03, 30.44,
       45.63, 37.45, 34.44, 34.93, 32.15, 66.48, 46.24, 38.89, 33.58,
       40.17, 52.4 , 59.98, 58.15, 43.77, 55.11, 43.62, 60.34, 48.22,
       70.56, 53.54, 66.37, 36.75, 40.13, 73.28, 36.45, 74.15, 43.4 ,
       40.88, 38.35, 54.8 , 63.15, 62.83, 35.15, 39.48, 29.93, 46.91,
       46.3 , 54.61, 42.25, 29.6 , 65.53, 41.25, 31.56, 58.01, 54.87,
       28.07, 20.32, 54.54, 45.71, 48.89, 29.24, 22.02, 32.44, 40.14,
       61.13, 57.76, 54.27, 56.87, 34.38, 27.79, 37.41, 43.91, 41.03,
       33.28, 39.1 , 31.82, 67.6 , 30.38, 48.58, 50.83, 45.09, 47.82,
       32.43, 26.47, 29.58, 28.22, 66.04, 39.83, 33.65, 60.21, 35.18,
       35.12, 58.46, 26.14, 30.31, 38.22, 35.89, 39.8 , 55.84, 49.92,
       50.16, 52.45, 51.33, 61.78, 52.41, 47.73, 31.29, 31.1 , 37.27,
       42.68, 32.32, 61.06, 48.21, 34.12, 30.69, 30.24, 28.53, 47.62,
       35.25, 23.47, 49.72, 36.21, 54.73, 22.82, 42.01, 28.58, 25.64,
       66.01, 46.5 , 57.85, 43.06, 49.85, 33.27, 27.84, 62.45, 55.42,
       37.78, 37.29, 32.33, 38.39, 42.79, 47.45, 54.62, 29.13, 39.98,
       28.68, 23.3 , 21.76, 38.63, 49.83, 38.84, 22.56, 67.59, 73.9 ,
       62.27, 57.86, 30.92, 24.5 , 20.23, 53.71, 34.65, 51.96, 58.  ,
       31.48, 57.39, 60.29, 73.68, 64.82, 73.45, 67.41, 72.2 , 69.34,
       79.11, 68.02, 76.01, 82.04, 58.02, 52.69, 81.59, 74.47, 76.24,
       57.3 , 67.33, 63.86, 64.39, 69.14, 66.08, 54.95, 60.31, 36.6 ,
       49.48, 69.6 , 54.93, 58.9 , 61.5 , 64.52, 65.85, 60.82, 53.85,
       39.53, 58.62, 65.94, 36.16, 72.53, 39.43, 54.48, 63.91, 66.44,
       52.27, 89.29, 54.66, 60.72, 77.32, 80.17, 51.72, 53.4 , 43.86,
       74.39, 76.32, 49.62, 48.91, 68.92, 74.98, 69.58, 64.53, 58.39,
       47.24, 61.77, 75.53, 47.55, 21.79, 72.46, 68.3 , 67.  , 52.65,
       59.03, 59.41, 48.99, 76.16, 51.31, 67.51, 82.32, 64.57, 75.73,
       85.61, 73.29, 78.75, 45.37, 42.62, 53.82, 68.79, 43.67, 59.79,
       52.38, 61.67, 40.57, 63.72, 63.84, 59.99, 62.52, 24.23, 72.95,
       67.44, 54.55, 86.42, 62.61, 63.27, 58.55, 60.01, 67.05, 23.85,
       58.16, 64.05, 65.1 , 61.09, 52.44, 77.38, 58.77, 78.72, 63.33,
       63.24, 23.36, 65.26, 50.22, 60.71, 62.6 , 69.26, 56.51, 76.2 ,
       76.69, 86.02, 69.22, 59.6 , 75.92, 69.7 , 45.62, 47.36, 74.16,
       78.25, 59.18, 21.73, 81.09, 70.16, 62.42, 75.52, 60.37, 61.14,
       47.19, 76.41, 84.79, 77.42, 48.5 , 69.61, 56.03, 76.47, 70.32,
       34.73, 68.93, 54.59, 74.86, 73.53, 57.31, 83.73, 74.8 , 51.75,
       52.16, 81.84, 78.26, 50.9 , 78.15, 76.65, 57.32, 36.3 , 72.78,
       65.18, 63.55, 49.96, 59.85, 69.64, 52.74, 56.81, 81.46, 40.8 ,
       81.87, 50.47, 38.02, 51.24, 66.93, 71.86, 24.43, 63.53, 69.32,
       78.02, 30.42, 52.79, 65.16, 78.74, 61.1 , 39.16, 66.22, 49.02,
       54.21, 58.13, 73.01, 53.83, 63.8 , 66.52, 49.88, 59.92, 54.9 ,
       57.75, 59.43, 44.15, 65.05, 67.09, 75.47, 88.57, 53.23, 75.35,
       66.74, 51.14, 40.99, 57.08, 55.39, 40.73, 40.56, 54.24, 53.37,
       56.02, 59.84, 75.32, 44.37, 46.65, 68.68, 83.64, 51.55, 63.32,
       59.62, 53.64, 74.23, 60.67, 54.81, 63.02, 58.84, 60.75, 71.7 ,
       75.21, 50.85, 67.02, 60.98, 65.39, 51.25, 45.82, 39.87, 70.67,
       73.36, 65.99, 72.69, 61.48, 65.06, 64.14, 55.73, 79.34, 74.81,
       63.07, 81.06, 53.24, 69.94, 60.94, 55.59, 75.94, 47.96, 71.41,
       25.22, 61.68, 47.83, 50.35, 72.27, 86.59, 38.59, 72.83, 66.88,
       55.99, 72.16, 33.02, 83.31, 43.71, 68.61, 79.5 , 67.89, 49.82,
       66.7 , 47.14, 61.6 , 49.43, 32.73, 65.11, 66.58, 62.77, 50.04,
       34.3 , 61.03, 77.97, 54.28, 51.09, 53.02, 78.69, 46.92, 48.68,
       51.56, 62.11, 58.05, 61.31, 66.3 , 64.12, 77.89, 85.18, 77.49,
       76.61])

In [24]:
df.age.fillna(df.age.mean())

0      51.30
1      38.72
2      35.17
3      32.78
4      31.51
       ...
857    77.89
858    85.18
859    77.49
860    63.33
861    76.61
Name: age, Length: 862, dtype: float64

Imputation has been performed to get rid of null values, using **SimpleImputer**

In [26]:
df = pd.DataFrame(SimpleImputer(strategy = "most_frequent").fit_transform(df),columns = df.columns)
df.isna().sum()

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

Grade                0
Project              0
Case_ID              0
Gender               0
age                  0
Primary_Diagnosis    0
Race                 0
IDH1                 0
TP53                 0
ATRX                 0
PTEN                 0
EGFR                 0
CIC                  0
MUC16                0
PIK3CA               0
NF1                  0
PIK3R1               0
FUBP1                0
RB1                  0
NOTCH1               0
BCOR                 0
CSMD3                0
SMARCA4              0
GRIN2A               0
IDH2                 0
FAT4                 0
PDGFRA               0
dtype: int64

In [27]:
df.head()

,Grade,Project,Case_ID,Gender,age,Primary_Diagnosis,Race,IDH1,TP53,ATRX,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,LGG,TCGA-LGG,TCGA-DU-8164,Male,51.3,"Oligodendroglioma, NOS",white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
1,LGG,TCGA-LGG,TCGA-QH-A6CY,Male,38.72,Mixed glioma,white,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
2,LGG,TCGA-LGG,TCGA-HW-A5KM,Male,35.17,"Astrocytoma, NOS",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
3,LGG,TCGA-LGG,TCGA-E1-A7YE,Female,32.78,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,MUTATED,NOT_MUTATED
4,LGG,TCGA-LGG,TCGA-S9-A6WG,Male,31.51,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED

### Getting rid of unwanted columns

In [39]:
df.Project

0      TCGA-LGG
1      TCGA-LGG
2      TCGA-LGG
3      TCGA-LGG
4      TCGA-LGG
         ...
857    TCGA-GBM
858    TCGA-GBM
859    TCGA-GBM
860    TCGA-GBM
861    TCGA-GBM
Name: Project, Length: 862, dtype: object

In [40]:
df.Case_ID

0      TCGA-DU-8164
1      TCGA-QH-A6CY
2      TCGA-HW-A5KM
3      TCGA-E1-A7YE
4      TCGA-S9-A6WG
           ...
857    TCGA-19-5959
858    TCGA-16-0846
859    TCGA-28-1746
860    TCGA-32-2491
861    TCGA-06-2557
Name: Case_ID, Length: 862, dtype: object

Here we can see that the columns Project and Case_ID do not contribute much to the Grade(target) of our dataset as all project sblong to the same category of brain tunor that is TCGA. Since all case IDs are the different fro different parients, thus we can't derive any correlation amongst the case id and the Target. Thus we will drop these columns.

In [29]:
df.drop(columns = ["Case_ID","Project"], inplace = True)

In [30]:
df.head()

,Grade,Gender,age,Primary_Diagnosis,Race,IDH1,TP53,ATRX,PTEN,EGFR,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,LGG,Male,51.3,"Oligodendroglioma, NOS",white,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,...,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
1,LGG,Male,38.72,Mixed glioma,white,MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
2,LGG,Male,35.17,"Astrocytoma, NOS",white,MUTATED,MUTATED,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED
3,LGG,Female,32.78,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,MUTATED,NOT_MUTATED
4,LGG,Male,31.51,"Astrocytoma, anaplastic",white,MUTATED,MUTATED,MUTATED,NOT_MUTATED,NOT_MUTATED,...,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED,NOT_MUTATED

## Label Encoding

Now converting all the categorical data in the dataset to numerical value using the LabelEncoder.

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
cols = list(df.columns)
cols.remove("age")

In [34]:
for x in cols:
    df[x] = LabelEncoder().fit_transform(df[x])

In [35]:
df.head()

,Grade,Gender,age,Primary_Diagnosis,Race,IDH1,TP53,ATRX,PTEN,EGFR,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,1,1,51.3,4,3,0,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
1,1,1,38.72,3,3,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,1,1,35.17,0,3,0,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
3,1,0,32.78,1,3,0,0,0,1,1,...,1,1,1,1,1,1,1,1,0,1
4,1,1,31.51,1,3,0,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [36]:
data = df.drop(columns = ['Grade'])
target = df.Grade
data.shape,target.shape

((862, 24), (862,))

# Pipeline and Cross Validation

Pipeline is object that transforms with the final estimator. It Applies a list of sequential transformation over the datset that applies. It fits and transforms the processes sequentially on the dataset. The final estimator is only fit in the pipline.

K-fold Cross-Validation is when the dataset is split into a K number of folds and is used to evaluate the model's ability when given new data. K refers to the number of groups the data sample is split into.

In [37]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.metrics import accuracy_score

In [38]:
def results(pipe, xtrain, ytrain, xtest, ytest):
    train_acc = pipe.score(xtrain, ytrain)
    test_acc = pipe.score(xtest, ytest)
    print("Training accuracy:",train_acc)
    print("Testing accuracy:",test_acc)
    print()
    return train_acc, test_acc

In [39]:
xtrain, xtest, ytrain, ytest = train_test_split(data,target, test_size = 0.3)

In [40]:
np.random.seed(0)

# k Nearest Neighbors

Finding the best value of K for applying the cross validation over the model

In [41]:
for i in range(2,16):
    knn = KNeighborsClassifier(n_neighbors = i,weights = 'distance')
    knn = knn.fit(xtrain, ytrain)
    ytrain_preds = knn.predict(xtrain)
    ytest_preds = knn.predict(xtest)
    print("For k:", i)
    print("Training Accuracy:",accuracy_score(ytrain, ytrain_preds))
    print("Testing Accuracy:",accuracy_score(ytest, ytest_preds))
    print()

For k: 2
Training Accuracy: 1.0
Testing Accuracy: 0.8918918918918919

For k: 3
Training Accuracy: 1.0
Testing Accuracy: 0.8803088803088803

For k: 4
Training Accuracy: 1.0
Testing Accuracy: 0.8841698841698842

For k: 5
Training Accuracy: 1.0
Testing Accuracy: 0.888030888030888

For k: 6
Training Accuracy: 1.0
Testing Accuracy: 0.8764478764478765

For k: 7
Training Accuracy: 1.0
Testing Accuracy: 0.8764478764478765

For k: 8
Training Accuracy: 1.0
Testing Accuracy: 0.8764478764478765

For k: 9
Training Accuracy: 1.0
Testing Accuracy: 0.8571428571428571

For k: 10
Training Accuracy: 1.0
Testing Accuracy: 0.8532818532818532

For k: 11
Training Accuracy: 1.0
Testing Accuracy: 0.8494208494208494

For k: 12
Training Accuracy: 1.0
Testing Accuracy: 0.8455598455598455

For k: 13
Training Accuracy: 1.0
Testing Accuracy: 0.833976833976834

For k: 14
Training Accuracy: 1.0
Testing Accuracy: 0.8301158301158301

For k: 15
Training Accuracy: 1.0
Testing Accuracy: 0.8185328185328186

Evaluating the model for 10 folds

In [87]:
def knn_evaluation():
    pipe = Pipeline([('sc',StandardScaler()),
                     ('pca',PCA()),
                     ('knn', KNeighborsClassifier(n_neighbors = 6,weights = 'distance'))])
    fold = 0
    a, b = 0, 0
    trainavg , testavg = 0, 0
    skf = StratifiedKFold(n_splits = 10)
    for trainindex, testindex in skf.split(data,target):
            fold += 1
            xtrain, xtest = data.iloc[trainindex], data.iloc[testindex]
            ytrain, ytest = target.iloc[trainindex], target.iloc[testindex]
            pipe.fit(xtrain, ytrain)
            print("For Fold", fold)
            a, b = results(pipe, xtrain, ytrain, xtest, ytest)
            trainavg += a
            testavg+= b
    print("Training accuracy average:", trainavg/10)
    print("Tresting accuracy average:", testavg/10)

In [88]:
knn_evaluation()

For Fold 1
Training accuracy: 1.0
Testing accuracy: 0.8505747126436781

For Fold 2
Training accuracy: 1.0
Testing accuracy: 0.8850574712643678

For Fold 3
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 4
Training accuracy: 1.0
Testing accuracy: 0.8372093023255814

For Fold 5
Training accuracy: 1.0
Testing accuracy: 0.8953488372093024

For Fold 6
Training accuracy: 1.0
Testing accuracy: 0.813953488372093

For Fold 7
Training accuracy: 1.0
Testing accuracy: 0.8023255813953488

For Fold 8
Training accuracy: 1.0
Testing accuracy: 0.8953488372093024

For Fold 9
Training accuracy: 1.0
Testing accuracy: 0.8488372093023255

For Fold 10
Training accuracy: 1.0
Testing accuracy: 0.9069767441860465

Training accuracy average: 1.0
Tresting accuracy average: 0.860772520716386

# Decision Trees

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
def dt_evaluation():
    pipe = Pipeline([('sc',StandardScaler()),
                     ('pca',PCA()),
                     ('dt', DecisionTreeClassifier())])
    fold = 0
    a, b = 0, 0
    trainavg , testavg = 0, 0
    skf = StratifiedKFold(n_splits = 10)
    for trainindex, testindex in skf.split(data,target):
            fold += 1
            xtrain, xtest = data.iloc[trainindex], data.iloc[testindex]
            ytrain, ytest = target.iloc[trainindex], target.iloc[testindex]
            pipe.fit(xtrain, ytrain)
            print("For Fold", fold)
            a, b = results(pipe, xtrain, ytrain, xtest, ytest)
            trainavg += a
            testavg+= b
    print("Training accuracy average:", trainavg/10)
    print("Tresting accuracy average:", testavg/10)

In [91]:
dt_evaluation()

For Fold 1
Training accuracy: 1.0
Testing accuracy: 0.8160919540229885

For Fold 2
Training accuracy: 1.0
Testing accuracy: 0.8390804597701149

For Fold 3
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 4
Training accuracy: 1.0
Testing accuracy: 0.8837209302325582

For Fold 5
Training accuracy: 1.0
Testing accuracy: 0.8372093023255814

For Fold 6
Training accuracy: 1.0
Testing accuracy: 0.8255813953488372

For Fold 7
Training accuracy: 1.0
Testing accuracy: 0.9069767441860465

For Fold 8
Training accuracy: 1.0
Testing accuracy: 0.8255813953488372

For Fold 9
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 10
Training accuracy: 1.0
Testing accuracy: 0.9186046511627907

Training accuracy average: 1.0
Tresting accuracy average: 0.8597032878909381

# SVM

In [92]:
from sklearn.svm import SVC

In [94]:
kernels = ['linear', 'poly', 'rbf']
def svc_evaluation():
    for x in kernels:
        pipe = Pipeline([('sc',StandardScaler()),
                         ('pca',PCA()),
                         ('dt', SVC(kernel = x))])
        fold = 0
        a, b = 0, 0
        print("For kernel:", x)
        trainavg , testavg = 0, 0
        skf = StratifiedKFold(n_splits = 10)
        for trainindex, testindex in skf.split(data,target):
                fold += 1
                xtrain, xtest = data.iloc[trainindex], data.iloc[testindex]
                ytrain, ytest = target.iloc[trainindex], target.iloc[testindex]
                pipe.fit(xtrain, ytrain)
                print("For Fold", fold)
                a, b = results(pipe, xtrain, ytrain, xtest, ytest)
                trainavg += a
                testavg+= b
        print("Training accuracy average:", trainavg/10)
        print("Tresting accuracy average:", testavg/10)
        print()

In [95]:
svc_evaluation()

For kernel: linear
For Fold 1
Training accuracy: 0.8735483870967742
Testing accuracy: 0.8735632183908046

For Fold 2
Training accuracy: 0.8748387096774194
Testing accuracy: 0.8620689655172413

For Fold 3
Training accuracy: 0.8711340206185567
Testing accuracy: 0.8953488372093024

For Fold 4
Training accuracy: 0.8762886597938144
Testing accuracy: 0.8488372093023255

For Fold 5
Training accuracy: 0.8737113402061856
Testing accuracy: 0.872093023255814

For Fold 6
Training accuracy: 0.875
Testing accuracy: 0.8604651162790697

For Fold 7
Training accuracy: 0.875
Testing accuracy: 0.8604651162790697

For Fold 8
Training accuracy: 0.8724226804123711
Testing accuracy: 0.8837209302325582

For Fold 9
Training accuracy: 0.8737113402061856
Testing accuracy: 0.872093023255814

For Fold 10
Training accuracy: 0.8698453608247423
Testing accuracy: 0.9069767441860465

Training accuracy average: 0.873550049883605
Tresting accuracy average: 0.8735632183908045

For kernel: poly
For Fold 1
Training accuracy: 0.8890322580645161
Testing accuracy: 0.8390804597701149

For Fold 2
Training accuracy: 0.8929032258064517
Testing accuracy: 0.8505747126436781

For Fold 3
Training accuracy: 0.884020618556701
Testing accuracy: 0.8604651162790697

For Fold 4
Training accuracy: 0.8827319587628866
Testing accuracy: 0.7906976744186046

For Fold 5
Training accuracy: 0.895618556701031
Testing accuracy: 0.8953488372093024

For Fold 6
Training accuracy: 0.895618556701031
Testing accuracy: 0.7906976744186046

For Fold 7
Training accuracy: 0.8969072164948454
Testing accuracy: 0.7558139534883721

For Fold 8
Training accuracy: 0.8775773195876289
Testing accuracy: 0.8372093023255814

For Fold 9
Training accuracy: 0.9020618556701031
Testing accuracy: 0.8488372093023255

For Fold 10
Training accuracy: 0.8788659793814433
Testing accuracy: 0.8837209302325582

Training accuracy average: 0.8895337545726637
Tresting accuracy average: 0.8352445870088212

For kernel: rbf
For Fold 1
Training accuracy: 0.896774193548387
Testing accuracy: 0.8735632183908046

For Fold 2
Training accuracy: 0.9006451612903226
Testing accuracy: 0.8505747126436781

For Fold 3
Training accuracy: 0.8981958762886598
Testing accuracy: 0.872093023255814

For Fold 4
Training accuracy: 0.8981958762886598
Testing accuracy: 0.8372093023255814

For Fold 5
Training accuracy: 0.9020618556701031
Testing accuracy: 0.872093023255814

For Fold 6
Training accuracy: 0.9007731958762887
Testing accuracy: 0.8372093023255814

For Fold 7
Training accuracy: 0.9020618556701031
Testing accuracy: 0.8604651162790697

For Fold 8
Training accuracy: 0.8994845360824743
Testing accuracy: 0.8837209302325582

For Fold 9
Training accuracy: 0.9020618556701031
Testing accuracy: 0.8488372093023255

For Fold 10
Training accuracy: 0.9020618556701031
Testing accuracy: 0.9069767441860465

Training accuracy average: 0.9002316262055204
Tresting accuracy average: 0.8642742582197274

# Random forest

In [96]:
from sklearn.ensemble import RandomForestClassifier

In [99]:
def rfc_evaluation():
    pipe = Pipeline([('sc',StandardScaler()),
                     ('pca',PCA()),
                     ('rf', RandomForestClassifier())])
    fold = 0
    a, b = 0, 0
    trainavg , testavg = 0, 0
    skf = StratifiedKFold(n_splits = 10)
    for trainindex, testindex in skf.split(data,target):
            fold += 1
            xtrain, xtest = data.iloc[trainindex], data.iloc[testindex]
            ytrain, ytest = target.iloc[trainindex], target.iloc[testindex]
            pipe.fit(xtrain, ytrain)
            print("For Fold", fold)
            a, b = results(pipe, xtrain, ytrain, xtest, ytest)
            trainavg += a
            testavg+= b
    print("Training accuracy average:", trainavg/10)
    print("Tresting accuracy average:", testavg/10)

In [100]:
rfc_evaluation()

For Fold 1
Training accuracy: 1.0
Testing accuracy: 0.896551724137931

For Fold 2
Training accuracy: 1.0
Testing accuracy: 0.9080459770114943

For Fold 3
Training accuracy: 1.0
Testing accuracy: 0.9186046511627907

For Fold 4
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 5
Training accuracy: 1.0
Testing accuracy: 0.9418604651162791

For Fold 6
Training accuracy: 1.0
Testing accuracy: 0.9069767441860465

For Fold 7
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 8
Training accuracy: 1.0
Testing accuracy: 0.9069767441860465

For Fold 9
Training accuracy: 1.0
Testing accuracy: 0.872093023255814

For Fold 10
Training accuracy: 1.0
Testing accuracy: 0.9186046511627907

Training accuracy average: 1.0
Tresting accuracy average: 0.9013900026730821

In [101]:
report_data = {"Models":["KNeighborsClassifier(k = 6)","DecisionTreeClassifier"," SVC(kernel = x)","RandomForestClassifier"],
               "Training Accuracy":["100%","100%","90%","100%"],
               "Testing Accuracy":["86.08%","86","86.42%","90.13%"]}

In [102]:
report_data

{'Models': ['KNeighborsClassifier(k = 6)',
  'DecisionTreeClassifier',
  ' SVC(kernel = x)',
  'RandomForestClassifier'],
 'Training Accuracy': ['100%', '100%', '90%', '100%'],
 'Testing Accuracy': ['86.08%', '86', '86.42%', '90.13%']}

In [103]:
report = pd.DataFrame(report_data)

In [104]:
report

                        Models Training Accuracy Testing Accuracy
0  KNeighborsClassifier(k = 6)              100%           86.08%
1       DecisionTreeClassifier              100%               86
2              SVC(kernel = x)               90%           86.42%
3       RandomForestClassifier              100%           90.13%

Thus we can see that Random Forest Classifier has the maximum accuracy of 90.13%, and thus performs better prediction over other models.